### ISSUE TITLE
FeatureRequest: Make translatable sphone

### ISSUE THREAD

**Issue by carlosgonz0** [maemo-leste/sphone#3]

**Comment by MerlijnWajer** [comment]
It might be better to file this here: https://github.com/maemo-leste/bugtracker/issues/

I think this might not be super hard, we would need to:

1. Identify the strings to translate
2. Use standard localisation tools to translate strings
3. Create a package for the localisation and have people translate on weblate

**Comment by carlosgonz0** [comment]
Thanks.
